version: '3.7'
services:
  mermaid-live-editor:
    image: ghcr.io/mermaid-js/mermaid-live-editor
    ports: 
      - "9080:80"

# https://github.com/mermaidjs/mermaid-live-editor
# https://github.com/mermaid-js/mermaid

  mock-server:
    image: up9inc/wiremock-studio:2.32.0-18
    ports: 
      - "8000-8100:8000-8100"
      - "9000:9000"
    volumes:
      - ./wiremock:/home/wiremock

# https://wiremock.org/studio/docs/getting-started/docker/